`Supervised Machine Learning - Regression`

In [15]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
housing_data = pd.read_csv('housing_data.csv')

In [16]:
housing_data.head(3)

Sq ft  Burglaries    Rent
0   916.0        15.0  2490.0
1   571.0         8.0   890.0
2  1019.0         7.0  2050.0

In [17]:
print(f'The number of rentals in the sample: {len(housing_data)}')

The number of rentals in the sample: 100


In [18]:
housing_data.Rent.dtype

dtype('float64')

In [19]:
# Separate the data into independent and dependent variables
X = housing_data[['Sq ft', 'Burglaries']].values
y = housing_data['Rent']
# Create the model
reg = LinearRegression()

# Train the model
reg.fit(X, y)

square_footage = 1250
number_of_burglaries = 10

y_pred = reg.predict(np.array([square_footage, number_of_burglaries]).reshape(1, 2))
print(y_pred)

[2830.02438661]


`Supervised Machine Learning - Classification`

In [20]:
# Import module
from sklearn.neighbors import KNeighborsClassifier

In [21]:
# Load the data
photo_id_times = pd.read_csv('photo_id_times.csv')

In [22]:
photo_id_times.value_counts()

Time to id photo  Class
-1.043271         0.0      1
 5.306796         0.0      1
 6.394511         1.0      1
 6.372915         1.0      1
 6.086478         1.0      1
                          ..
 3.208621         0.0      1
 3.100049         0.0      1
 3.066562         0.0      1
 3.029407         0.0      1
 10.007348        1.0      1
Name: count, Length: 100, dtype: int64

In [23]:
# Separate the data into independent and dependent variables
X = np.array(photo_id_times['Time to id photo']).reshape(-1, 1)
y = photo_id_times['Class']

# Create a model and fit it to the data
neigh = KNeighborsClassifier(n_neighbors=3)
neigh.fit(X, y)

time_to_identify_picture = 5

# Make a prediction based on how long it takes to identify a picture
y_pred = neigh.predict(np.array(time_to_identify_picture).reshape(1, -1))

if y_pred == 1:
    print("We think you're a robot.")
else:
    print("Welcome, human!")


Welcome, human!


In [24]:
array_trial = np.array([[10, 30], [40, 40]])

In [25]:
array_trial

array([[10, 30],
       [40, 40]])

In [26]:
np.reshape(array_trial, (1,-1))

array([[10, 30, 40, 40]])

In [27]:
array_trial

array([[10, 30],
       [40, 40]])

In [28]:
from sklearn.cluster import KMeans
from plot import plot_clusters

# Load the data
media_usage = pd.read_csv('media_usage.csv')

# Create the model
kmeans = KMeans(n_clusters=3)

# Fit the model to the data
kmeans.fit(media_usage)

labels = kmeans.predict(media_usage)

# Plot the clusters
plot_clusters(media_usage, labels)

ImportError: cannot import name 'plot_clusters' from 'plot' (C:\Users\stank\AppData\Roaming\Python\Python311\site-packages\plot\__init__.py)