`Supervised Machine Learning - Regression`

In [23]:
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.linear_model import LinearRegression
housing_data = pd.read_csv('housing_data.csv')

In [24]:
housing_data.head(3)

Sq ft  Burglaries    Rent
0   916.0        15.0  2490.0
1   571.0         8.0   890.0
2  1019.0         7.0  2050.0

In [25]:
print(f'The number of rentals in the sample: {len(housing_data)}')

The number of rentals in the sample: 100


In [26]:
housing_data.Rent.dtype

dtype('float64')

In [27]:
# Separate the data into independent and dependent variables
X = housing_data[['Sq ft', 'Burglaries']].values
y = housing_data['Rent']
# Create the model
reg = LinearRegression()

# Train the model
reg.fit(X, y)

square_footage = 1250
number_of_burglaries = 10

y_pred = reg.predict(np.array([square_footage, number_of_burglaries]).reshape(1, -1))
print(y_pred)

[2830.02438661]


`Supervised Machine Learning - Classification`

In [28]:
# Import module
from sklearn.neighbors import KNeighborsClassifier

In [29]:
# Load the data
photo_id_times = pd.read_csv('photo_id_times.csv')

In [30]:
photo_id_times.value_counts()

Time to id photo  Class
-1.043271         0.0      1
 5.306796         0.0      1
 6.394511         1.0      1
 6.372915         1.0      1
 6.086478         1.0      1
                          ..
 3.208621         0.0      1
 3.100049         0.0      1
 3.066562         0.0      1
 3.029407         0.0      1
 10.007348        1.0      1
Name: count, Length: 100, dtype: int64

In [31]:
photo_id_times['Time to id photo']

0     3.538784
1     1.674163
2     2.697005
3     0.506161
4     2.344700
        ...   
95    8.221441
96    5.256662
97    8.059844
98    3.887342
99    5.086033
Name: Time to id photo, Length: 100, dtype: float64

In [32]:
np.array(photo_id_times['Time to id photo'])

array([ 3.53878426e+00,  1.67416312e+00,  2.69700513e+00,  5.06160528e-01,
        2.34469970e+00,  1.34215306e+00,  1.38935045e+00,  3.97947879e+00,
        3.77926640e+00,  4.59492153e+00,  2.50572279e+00,  2.92856494e+00,
        1.52631899e+00, -3.11709107e-01,  4.68628277e+00,  3.23051130e+00,
        4.58157362e+00,  3.27303772e+00,  5.82892290e+00,  3.20862108e+00,
        3.01091534e+00,  2.62724367e+00,  5.40830930e+00,  3.64817650e+00,
        2.03385290e+00,  5.08577340e+00,  3.73191522e+00,  4.73851339e+00,
        3.10004888e+00,  4.64682028e+00,  3.62147781e+00,  1.53345917e+00,
        3.37054282e+00,  4.40753444e+00,  3.02940719e+00,  3.40198951e+00,
        3.06656176e+00,  3.30626356e+00,  5.30679576e+00,  3.86206793e+00,
        1.55076580e+00,  5.02693254e+00,  5.04967228e+00,  2.57129148e+00,
        6.02473607e+00,  4.08780139e+00,  7.05284255e-03,  3.64441021e+00,
        1.64064626e+00,  2.65082790e+00,  2.40163340e+00,  4.68055521e+00,
        1.32440414e+00,  

In [33]:
# Separate the data into independent and dependent variables
X = np.array(photo_id_times['Time to id photo']).reshape(-1, 1)
y = photo_id_times['Class']

# Create a model and fit it to the data
neigh = KNeighborsClassifier(n_neighbors=3)
neigh.fit(X, y)

time_to_identify_picture = 10

# Make a prediction based on how long it takes to identify a picture
y_pred = neigh.predict(np.array(time_to_identify_picture).reshape(1, -1))

if y_pred == 1:
    print("We think you're a robot.")
else:
    print("Welcome, human!")


We think you're a robot.


In [34]:
array_trial = np.array([[10, 30], [40, 40]])

In [35]:
array_trial

array([[10, 30],
       [40, 40]])

In [36]:
np.reshape(array_trial, (1, -1))

array([[10, 30, 40, 40]])

In [37]:
array_trial

array([[10, 30],
       [40, 40]])

In [38]:
from sklearn.cluster import KMeans
from plot import plot_clusters
import warnings
warnings.filterwarnings("ignore")
# Load the data
media_usage = pd.read_csv('media_usage.csv')

# Create the model
kmeans = KMeans(n_clusters=3)

# Fit the model to the data
kmeans.fit(media_usage)

labels = kmeans.predict(media_usage)

# Plot the clusters
plot_clusters(media_usage, labels)

AttributeError: 'NoneType' object has no attribute 'split'

In [ ]:
np.array([True, 1, 2]) + np.array([3, 4, False])

In [ ]:
np.array([4,5,2])

In [ ]:
[True, 1, 2] + [3, 4, False]

In [ ]:
np.array([True, 1, 2])

In [ ]:
np.array([3, 4, False])

In [ ]:
import numpy as np

In [ ]:
np.random.seed(300)

In [ ]:
tails_num = []
for _ in range(10000):
    output = []
    tails = [0]
    for i in range(10):
        result = np.random.randint(0,2)
        if result == 0:
            output.append('heads')
        else:
            output.append('tails')
        tails.append(tails[i]+result)
    tails_num.append(tails[-1])
print(output)
#print(tails)
#print(tails_num)
print(f'The number of tails is {tails[-1]} after {len(output)} flips')

sns.histplot(tails_num, bins=10, color='red')
plt.title(f'Distribution of tails after {len(output)} flips repeated {len(tails_num)} times')
plt.xlabel('Number of tails (ranges)')
plt.ylabel('Frequency')
plt.show()
plt.clf()

In [ ]:
# Simulate random walk 10 times
all_walks = []
for _ in range(5) :
    random_walk = [0]
    for _ in range(100) :
        step = random_walk[-1]
        dice = np.random.randint(1,7)
        if dice <= 2:
            step = max(0, step - 1)
        elif dice <= 5:
            step = step + 1
        else:
            step = step + np.random.randint(1,7)

        # Implement clumsiness
        clum = np.random.rand()
        if clum <= 0.005 :
            step = 0

        random_walk.append(step)
    all_walks.append(random_walk)

# Create and plot np_aw_t
np_aw_t = np.transpose(np.array(all_walks))
plt.plot(np_aw_t)
plt.title('Number of rollings a dice and steps taken')
plt.xlabel('Number of rollings')
plt.ylabel('Number of steps')
plt.text(x=0 , y=50 , s=f'''The experiment includes
{len(random_walk)-1} rollings repeated {len(all_walks)} times''', fontsize=8)
plt.show()

In [ ]:
all_walks1 = []
for _ in range(500) :
    random_walk = [0]
    for _ in range(100) :
        step = random_walk[-1]
        dice = np.random.randint(1,7)
        if dice <= 2:
            step = max(0, step - 1)
        elif dice <= 5:
            step = step + 1
        else:
            step = step + np.random.randint(1,7)

        # Implement clumsiness
        clum = np.random.rand()
        if clum <= 0.001 :
            step = 0

        random_walk.append(step)
    all_walks1.append(random_walk)
np_aw_t_n = np.transpose(np.array(all_walks1))


In [ ]:
sns.histplot(np_aw_t_n[-1,:])
plt.show()
plt.clf()

In [ ]:
list = [[1, 2, 3,], [4, 5, 6]]

In [ ]:
list

In [ ]:
np.array(list)

In [ ]:
np.array(list).T